# https://render.com/docs/blueprint-spec
#

previewsEnabled: false

envVarGroups:
#   NOTE: This is for documentation purposes and isn’t supported by Render
#
# - name: SSH keys
#   secretFiles:
#     - fileName: id_ed25519
#       sync: false
#     - fileName: id_ed25519.pub
#       sync: false
#     - fileName: known_hosts
#       sync: false

- name: 'Static site repository (Git)'
  envVars:
    - key: GITHUB_REPOSITORY
      sync: false
    - key: GITHUB_BRANCH
      sync: false
    - key: GITHUB_USER_EMAIL
      sync: false
    - key: GITHUB_USER_NAME
      sync: false

- name: 'Apache authentication client (request header)'
  envVars:
    - key: AUTHORIZATION_HEADER_VALUE
      sync: false

services:
- type: web
  name: dollyskettle.com
  env: docker
  dockerfilePath: ./Dockerfile
  dockerContext: ./
  autoDeploy: false
  region: oregon
  plan: standard
  disk:
    name: git-repository
    mountPath: /home/deno/git-repository
    sizeGB: 70
  envVars:
  - fromGroup: 'SSH keys'
  - fromGroup: 'Static site repository (Git)'
  - fromGroup: 'Apache authentication client (request header)'
